### ISSUE TITLE
Problem with import

### ISSUE THREAD

**Issue by nirvana1122** [ClimbsRocks/auto_ml#312] opened 2017-08-04 12:49 UTC
Hi - I had problem installing auto_ml on my windows comp. I got the following error.

Requirement already satisfied: h5py in c:\anaconda3\lib\site-packages (from auto_ml)
Requirement already satisfied: dill in c:\anaconda3\lib\site-packages (from auto_ml)
Requirement already satisfied: pandas in c:\anaconda3\lib\site-packages (from auto_ml)
Requirement already satisfied: python-dateutil in c:\anaconda3\lib\site-packages (from auto_ml)
Exception:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "C:\Anaconda3\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "C:\Anaconda3\lib\email\feedparser.py", line 178, in feed
    self._input.push(data)
  File "C:\Anaconda3\lib\email\feedparser.py", line 104, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

I cloned the repository and did succeed in installing it using the setup.py. Now it's giving me problem with import. 

from auto_ml import Predictor

C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):

  File "<ipython-input-1-dd6fb37fc311>", line 1, in <module>
    from auto_ml import Predictor

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "C:\Anaconda3\lib\site-packages\auto_ml-2.5.0-py3.5.egg\auto_ml\__init__.py", line 6, in <module>
    from auto_ml.predictor import Predictor

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "C:\Anaconda3\lib\site-packages\auto_ml-2.5.0-py3.5.egg\auto_ml\predictor.py", line 37, in <module>
    from auto_ml import utils_model_training

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "C:\Anaconda3\lib\site-packages\auto_ml-2.5.0-py3.5.egg\auto_ml\utils_model_training.py", line 13, in <module>
    from auto_ml import utils_models

 File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "C:\Anaconda3\lib\site-packages\auto_ml-2.5.0-py3.5.egg\auto_ml\utils_models.py", line 18, in <module>
    from xgboost import XGBClassifier, XGBRegressor

  File "C:\Anaconda3\lib\site-packages\xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster

  File "C:\Anaconda3\lib\site-packages\xgboost\core.py", line 112, in <module>
    _LIB = _load_lib()

  File "C:\Anaconda3\lib\site-packages\xgboost\core.py", line 106, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])

  File "C:\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)

  File "C:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found

Does anyone knows what's going on? I know that I have XBBoost installed and working on my computer. Any help would be appreciated.

Thanks!

**Comment by ClimbsRocks** [comment] 2017-08-16 17:10
Strange. Have you tried modifying your PYTHONPATH to make sure it includes XGB? also, it looks like you're using anaconda's Python- are you sure that Anaconda knows where XGB is? 

Basically, even if you have xgb installed on your computer, anaconda might not know about it. try opening up an interactive python shell using anaconda's python, and importing xgboost. 

good luck!

**Comment by ClimbsRocks** [comment] 2017-09-09 02:05
i'm going to close this, as it appears to be an issue not specific to auto_ml. if you find anything that is caused by us, please open a new issue and let me know! thanks for being willing to share, and sharing the full stacktrace.

**Closed by ClimbsRocks** 2017-09-09 02:05 UTC
