### ISSUE TITLE
Issue with NLP data.

### ISSUE THREAD

**Issue by shaneconner** [ClimbsRocks/auto_ml#363] opened 2017-12-11 18:46 UTC
I'm unable to finish training my model that uses only NLP data --it keeps freezing up while attempting to calculate the feature responses. Here's the resulting error:

AttributeError: 'DataFrame' object has no attribute 'Importance', 'Delta', 'FR_Decrementing', 'FR_Incrementing', 'FRD_abs', 'FRI_abs'

I believe this is because of the sparse matrix NLP data creates which primarily contains NaN values in each column and subsequently warps statistical calculations so the feature response dataframe is unable to get formed.

To offset, I set ml_for_analytics=False but still receiving the following error:

AttributeError: 'DataFrame' object has no attribute 'FR_Incrementing'

Any effort to resolve this error is appreciated. Great work on this by the way!

**Comment by ClimbsRocks** [comment] 2017-12-14 21:36
oh sweet- thanks for letting me know! odd that that didn't get picked up by the test suite. i'll try to fix that up today or tomorrow, and certainly before next monday, unless the issue isn't what i expect it to be

**Comment by black-snow** [comment] 2018-01-02 17:06
Sounds related to https://github.com/ClimbsRocks/auto_ml/issues/366

**Comment by HalaKuwatly** [comment] 2018-01-11 10:50
is this fixed? I am getting the same error

**Comment by ClimbsRocks** [comment] 2018-02-09 00:27
sorry 'bout the delay! testing a fix for this now. should be released tonight.

**Comment by ClimbsRocks** [comment] 2018-02-09 18:24
fixed in last night's v2.9.9 release available on pypi (`pip install --upgrade auto_ml`)

**Closed by ClimbsRocks** 2018-02-09 18:24 UTC

**Comment by HalaKuwatly** [comment] 2018-02-15 12:13
Thanks. Can you give a working code example of a classification task with NLP data ? I can't get it to work.
