### ISSUE TITLE
Error training dataset

### ISSUE THREAD

**Issue by seigpe** [ClimbsRocks/auto_ml#383] opened 2018-02-08 22:58 UTC
Hi.

Training a dataset, this is the problem I have.

Here are the results from our GradientBoostingClassifier
predicting y
Calculating feature responses, for advanced analytics.
/usr/local/lib/python3.5/dist-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
Traceback (most recent call last):
  File "test_automl.py", line 600, in <module>
    ml_predictor.train(X_train)
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 641, in train
    self.trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, X_df, y)
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 1204, in train_ml_estimator
    trained_final_model = self.fit_single_pipeline(X_df, y, estimator_names[0], feature_learning=feature_learning, prediction_interval=False)
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 856, in fit_single_pipeline
    self.print_results(model_name, ppl, X_df, y)
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 1027, in print_results
    feature_responses = self.create_feature_responses(model, X, y, top_features)
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 994, in create_feature_responses
    all_results = list(map(lambda tup: create_one_feature_response(col_idx=tup[0], col_name=tup[1]), enumerate(feature_names)))
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 994, in <lambda>
    all_results = list(map(lambda tup: create_one_feature_response(col_idx=tup[0], col_name=tup[1]), enumerate(feature_names)))
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 945, in create_one_feature_response
    X[:, col_idx] += col_delta
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

**Comment by ClimbsRocks** [comment] 2018-02-09 02:07
bah, you're just a few hours too early! i'll have a new release out tonight that works around this. 

any chance you have code/dataset you can share that reproduces this error? i can prevent it from erroring, but i'm still not sure what the root cause is, and i'd love to solve that.

**Comment by ClimbsRocks** [comment] 2018-02-09 18:20
fixed in the v2.9.9 release available on pypi (`pip install --upgrade auto_ml`)

**Closed by ClimbsRocks** 2018-02-09 18:20 UTC

**Comment by seigpe** [comment] 2018-02-11 22:50
Yep, Works fine. My dataset is big, is any way to start in debug mode and send you the info?

On the other hand, with the same dataset I'm trying to use DeepLearningClassifier. I have the following error:


We will stop training early if we have not seen an improvement in validation accuracy in 25 epochs
To measure validation accuracy, we will split off a random 10 percent of your training data set
Traceback (most recent call last):
  File "star_automl_dl.py", line 605, in <module>
    ml_predictor.train(X_train, model_names=['DeepLearningClassifier'])
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 657, in train
    self.trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, X_df, y)
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 1223, in train_ml_estimator
    trained_final_model = self.fit_single_pipeline(X_df, y, estimator_names[0], feature_learning=feature_learning, prediction_interval=False)
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/predictor.py", line 862, in fit_single_pipeline
    ppl.fit(X_df, y)
  File "/usr/local/lib/python3.5/dist-packages/auto_ml/utils_model_training.py", line 148, in fit
    self.model.fit(X_fit, y, callbacks=callbacks, validation_data=(X_test, y_test), verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/keras/wrappers/scikit_learn.py", line 207, in fit
    return super(KerasClassifier, self).fit(x, y, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/wrappers/scikit_learn.py", line 151, in fit
    history = self.model.fit(x, y, **fit_args)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 965, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1614, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1430, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 70, in _standardize_input_data
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 70, in <listcomp>
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
AttributeError: 'int' object has no attribute 'ndim'


Any idea?
