### ISSUE TITLE
compare_all_models=True

### ISSUE THREAD

**Issue by PaulVanDev** [ClimbsRocks/auto_ml#347] opened 2017-11-02 10:22 UTC
Hi,
this module is really great, on the first tests, it gave me excellent results.
But one of the reasons I found your module is that I wanted to find a way to try several algos and select the best one.
in - what it does -   "6. Model Selection (which model works best for your problem)."

Is is the case or do we need to activate the option with "compare_all_models=True" that I found in the code? so is it correct then that GRadientBoostingclassifier will be matched to logistic and randomforset classifier?
Well I tried this option, and I got the following error

********************************************************************************************
About to run GridSearchCV on the pipeline for several models to predict seizure_state
Fitting 2 folds for each of 3 candidates, totalling 6 fits
------------------------------------------------
AttributeError Traceback (most recent call last)
<ipython-input-11-ac5e05ff2a58> in <module>()
      7 
      8 ml_predictor = Predictor(type_of_estimator='classifier', column_descriptions=column_descriptions)
----> 9 ml_predictor.train(data_d1[feature_columns],compare_all_models=True,ml_for_analytics=True)
     10 

C:\Users\pv\Anaconda3\lib\site-packages\auto_ml\predictor.py in train(self, raw_training_data, user_input_func, optimize_final_model, write_gs_param_results_to_file, perform_feature_selection, verbose, X_test, y_test, ml_for_analytics, take_log_of_y, model_names, perform_feature_scaling, calibrate_final_model, _scorer, scoring, verify_features, training_params, grid_search_params, compare_all_models, cv, feature_learning, fl_data, optimize_feature_learning, train_uncertainty_model, uncertainty_data, uncertainty_delta, uncertainty_delta_units, calibrate_uncertainty, uncertainty_calibration_settings, uncertainty_calibration_data, uncertainty_delta_direction, advanced_analytics, analytics_config, prediction_intervals, predict_intervals, ensemble_config, trained_transformation_pipeline, transformed_X, transformed_y, return_transformation_pipeline, X_test_already_transformed)
    637 
    638         # This is our main logic for how we train the final model
--> 639         self.trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, X_df, y)
    640 
    641         if self.ensemble_config is not None and len(self.ensemble_config) > 0:

C:\Users\pv\Anaconda3\lib\site-packages\auto_ml\predictor.py in train_ml_estimator(self, estimator_names, scoring, X_df, y, feature_learning, prediction_interval)
   1172             self.grid_search_params = grid_search_params
   1173 
-> 1174             gscv_results = self.fit_grid_search(X_df, y, grid_search_params, refit=True)
   1175 
   1176             trained_final_model = gscv_results.best_estimator_

C:\Users\pv\Anaconda3\lib\site-packages\auto_ml\predictor.py in fit_grid_search(self, X_df, y, gs_params, feature_learning, refit)
   1117                 # Note that we will only report analytics results on the final model that ultimately gets selected, and trained on the entire dataset
   1118 
-> 1119         gs.fit(X_df, y)
   1120 
   1121         if self.verbose:

C:\Users\pv\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py in fit(self, X, y, groups, **fit_params)
    637                                   error_score=self.error_score)
    638           for parameters, (train, test) in product(candidate_params,
--> 639                                                    cv.split(X, y, groups)))
    640 
    641         # if one choose to see train score, "out" will contain train score info

C:\Users\pv\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in __call__(self, iterable)
    787                 # consumption.
    788                 self._iterating = False
--> 789             self.retrieve()
    790             # Make sure that we get a last message telling us we are done
    791             elapsed_time = time.time() - self._start_time

C:\Users\pv\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in retrieve(self)
    697             try:
    698                 if getattr(self._backend, 'supports_timeout', False):
--> 699                     self._output.extend(job.get(timeout=self.timeout))
    700                 else:
    701                     self._output.extend(job.get())

C:\Users\pv\Anaconda3\lib\multiprocessing\pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

C:\Users\pv\Anaconda3\lib\multiprocessing\pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    383                         break
    384                     try:
--> 385                         put(task)
    386                     except Exception as e:
    387                         job, ind = task[:2]

C:\Users\pv\Anaconda3\lib\site-packages\sklearn\externals\joblib\pool.py in send(obj)
    369             def send(obj):
    370                 buffer = BytesIO()
--> 371                 CustomizablePickler(buffer, self._reducers).dump(obj)
    372                 self._writer.send_bytes(buffer.getvalue())
    373             self._send = send

C:\Users\pv\Anaconda3\lib\site-packages\auto_ml\predictor.py in _pickle_method(m)
     53 
     54 def _pickle_method(m):
---> 55     if m.im_self is None:
     56         return getattr, (m.im_class, m.im_func.func_name)
     57     else:

AttributeError: 'function' object has no attribute 'im_self'

**Comment by ClimbsRocks** [comment] 2017-11-02 21:19
ugh, that's the kind of error i hate. 

it's some weird combination of windows, python version, parallelism, and pickling/pathos. 

i'm probably not going to be a ton of help fixing this one, because it's pretty environment specific. i'm gonna give the answer i hate of "it works in our test suite and in all the environments i can run it in", but that doesn't help you, because you're on windows and probably can't just switch over to a linux environment. 

i'll tell you what i can:

- the issue is caused when we go to pickle either a function or a method before creating a new process to run it in. this is part of how sklearn parallelizes GridSearchCV
- if you feel like modifying the source code to try things out, you can comment out some lines at the start of `predictor.py` that deal with copy_reg: lines 54 - 65 here https://github.com/ClimbsRocks/auto_ml/blob/master/auto_ml/predictor.py#L54
- you might be able to solve the issue by switching to a different version of python
- you almost certainly will be able to solve the issue by switching to a unix environment (that's what our test suite uses. we have a test for this in our test suite, and it passes)


or, you can sidestep the issue entirely, and just train up individual predictors and compare them manually. this is obviously inelegant and not the ideal solution. but, you can easily change model names with `ml_predictor.train(data, model_names='GradientBoostingClassifer')` and changing it to something like `ml_predictor.train(data, model_names='RandomForestClassifier')`

i'm really sorry i'm not more help. i think the modifying source code approach might work. if you do, try cloning down this project to whatever director you're doing ML in, and then in your script before you have `from auto_ml import Predictor` put something like
```
import os
import sys
sys.path.insert(0, os.path.join(os.getcwd(), 'auto_ml'))
```
and that will import your local copy of auto_ml. you'll probably also have to `pip uninstall auto_ml` from your env, so it doesn't get confused. 

if you do solve this, please let me know! i don't have any windows boxes to dev on, so i'm always hungry to learn what i can do to make this more cross-platform compatible. 

thanks for filing the bug! hope it's an easy one to resolve.

**Comment by ClimbsRocks** [comment] 2017-11-10 20:05
@PaulVanDev I think i fixed this in the latest release! try upgrading to 2.8.4 and you should be good to go. closing this out now, but feel free to reopen if the issue persists. 

would love any other feedback you have!

**Closed by ClimbsRocks** 2017-11-10 20:05 UTC

**Comment by PaulVanDev** [comment] 2017-11-10 20:39
Thanks, i ll try next week and i ll tell you

**Comment by PaulVanDev** [comment] 2017-11-13 13:21
Ok, it does something, it works, and ended properly. Now I 've to look at what has been done. Thanks!
