### ISSUE TITLE
get_boston_dataset data while using  'DeepLearningRegressor', 'XGBRegressor'

### ISSUE THREAD

**Issue by odykai2009** [ClimbsRocks/auto_ml#319] opened 2017-08-28 21:24 UTC
I am having trouble while using the sample "get_boston_dataset" while running this code:

df_train, df_test = get_boston_dataset()
column_descriptions = {'MEDV': 'output', 'CHAS': 'categorical'}
ml_predictor = Predictor(type_of_estimator='regressor', column_descriptions=column_descriptions)
process_train = ml_predictor.train(df_train, model_names=['DeepLearningRegressor', 'XGBRegressor'])
#process_train = ml_predictor.train(df_train, model_names=['XGBRegressor'])

for 'DeepLearningRegressor':
AssertionError: epochs is not a legal parameter

for 'XGBRegressor':
print('It appears you are trying to use a library that is not available when we try to import it, or using a value for model_names that we do not recognize')
KeyError: 'XGBRegressor'

my library version:
sklearn==0.18
tensorflow==0.12.1
keras==1.0.7
xgboost==0.6

**Comment by ClimbsRocks** [comment] 2017-09-09 02:19
sorry for the slow response- was out in the desert without internet for a while. 

the `DeepLearningRegressor` error is almost certainly caused by the old version of tensorflow. try upgrading it to the latest with `pip install --upgrade tensorflow` (or, to upgrade all packages auto_ml relies on, `pip install --upgrade auto_ml`). 

the xgboost error is very likely because your python doesn't know where xgboost is installed. this happens all the time, unfortunately. try adding the location of xgboost to your `PATH` or `PYTHONPATH` in your `.bash_profile`. 

as an aside, try using microsoft's lightgbm as a replacement for xgboost. it's generally faster, and easier to install, while being comparably accurate. 

i'm going to close this issue, because it looks like it's specific to your environment, but please feel free to open another issue if one comes up! or feel free to post it on stackoverflow, and link it here, and i'll respond if no one beats me to it.

**Closed by ClimbsRocks** 2017-09-09 02:19 UTC
